name: "Build"

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository'
        required: true
        type: string
      branch:
        description: 'Branchname'
        required: true
        default: dev
        type: string
      solution:
        description: 'Solution'
        reqiered: true
        type: string
      publishtype:
        description: 'Publish-Type'
        default: 'WebPublish'
        type: string
jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.events.inputs.repository }}
        ref: ${{ github.events.inputs.branch }}
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE1

    - name: Setup NuGet
      run: |
        Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        nuget sources add -Source https://nuget.pkg.github.com/medientank-handels-gmbh/index.json -username ${{ secrets.WORKFLOW_USERNAME }} -password ${{ secrets.WORKFLOWNUGETTOKKEN }}   

    - name: Create Build Directory
      run: mkdir ${{ github.workspace }}\_build
      
    - name: Restore Packages
      run: nuget restore IO.Swagger.sln

    - name: Build Solution
      run: msbuild.exe ${{ github.events.inputs.solution }}.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=${{ github.events.inputs.publishtype }} /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl='${{ github.workspace }}\_build'
    
    - name: Zip Build
      run: Compress-Archive -Path '${{ github.workspace }}\_build' -DestinationPath '.\${{ github.events.inputs.solution }}.zip'
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.events.inputs.solution }}
        path: .\${{ github.events.inputs.solution }}.zip
        if-no-files-found: error
